name: .NET Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Get and update the build version
      - name: Set build version
        id: versioning
        run: |
          # Extract version from the .csproj file
          current_version=$(grep -oPm1 "(?<=<Version>)[^<]+" ./SampleDotNetApp.csproj)
          echo "Current version: $current_version"

          # Extract major and minor version
          major_version=$(echo $current_version | cut -d. -f1)
          minor_version=$(echo $current_version | cut -d. -f2)
          
          # Auto-increment build number using the GitHub run number
          build_number=$(( $GITHUB_RUN_NUMBER ))

          # Construct the new version (major.minor.build)
          new_version="${major_version}.${minor_version}.${build_number}"
          echo "New version: $new_version"

          # Make the new version available to other steps
          echo "VERSION=$new_version" >> $GITHUB_ENV

      # Step 5: Build the project with the new version
      - name: Build project
        run: dotnet build -c Release /p:Version=${{ env.VERSION }}

      # Step 6: Package the build
      - name: Package project
        run: dotnet publish -c Release -o ./output

      # Step 7: Upload the artifact to JFrog Artifactory
      - name: Upload .NET artifact to JFrog Artifactory
        run: |
          jfrog rt u "output/*" "test/SampleDotNetApp/${{ env.VERSION }}/" --build-name=dotnet-build --build-number=${{ github.run_id }}
        env:
          JFROG_URL: ${{ secrets.JFROG_URL }}
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
